apiVersion: v2
name: sloth-rules
description: SLO definition and implementation for Giant Swarm infrastructure
type: application
home: https://github.com/giantswarm/sloth-rules
kubeVersion: ">= 1.19.0-0"
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: atlas
