apiVersion: v2
name: sloth-rules
description: SLO definition and implementation for Giant Swarm infrastructure
type: application
home: https://github.com/giantswarm/sloth-rules
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
kubeVersion: ">= 1.19.0-0"
version: 0.35.1
annotations:
  application.giantswarm.io/team: atlas
  config.giantswarm.io/version: 1.x.x
