version: 2.1
orbs:
  architect: giantswarm/architect@6.12.0

jobs:
  check-generated:
    machine: true
    steps:
    - checkout
    - run:
        command: |
          make generate
          git diff --output /dev/null --exit-code helm/ || (echo 'Detected changes in generated files. Please run "make generate" and push again' && exit 1)
workflows:
  package-and-push-chart-on-tag:
    jobs:
    - check-generated:
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-app-catalog:
        name: push-sloth-rules-to-control-plane-catalog
        context: architect
        executor: app-build-suite
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: sloth-rules
        requires:
        - check-generated
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
