version: 2.1
orbs:
  architect: giantswarm/architect@5.11.1

jobs:
  check-generated:
    machine: true
    steps:
    - checkout
    - run:
        command: |
          make generate
          git diff --output /dev/null --exit-code helm/ || (echo 'Detected changes in generated files. Please run "make generate" and push again' && exit 1)
workflows:
  package-and-push-chart-on-tag:
    jobs:
    - check-generated:
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-app-catalog:
        name: push-sloth-rules-to-control-plane-catalog
        context: architect
        executor: app-build-suite
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: sloth-rules
        requires:
        - check-generated
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-collection:
        name: aws-app-collection
        context: architect
        app_catalog: control-plane-catalog
        app_name: sloth-rules
        app_namespace: monitoring
        app_collection_repo: aws-app-collection
        requires:
        - push-sloth-rules-to-control-plane-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        name: vsphere-app-collection
        context: architect
        app_catalog: control-plane-catalog
        app_name: sloth-rules
        app_namespace: monitoring
        app_collection_repo: vsphere-app-collection
        requires:
        - push-sloth-rules-to-control-plane-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-cloud-director-app-collection
        app_catalog: control-plane-catalog
        app_name: sloth-rules
        app_namespace: monitoring
        app_collection_repo: cloud-director-app-collection
        requires:
        - push-sloth-rules-to-control-plane-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-capa-app-collection
        app_catalog: control-plane-catalog
        app_name: sloth-rules
        app_namespace: monitoring
        app_collection_repo: capa-app-collection
        requires:
        - push-sloth-rules-to-control-plane-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-capz-app-collection
        app_catalog: control-plane-catalog
        app_name: sloth-rules
        app_namespace: monitoring
        app_collection_repo: capz-app-collection
        requires:
        - push-sloth-rules-to-control-plane-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
