version: 2.1
orbs:
  architect: giantswarm/architect@4.31.0

jobs:
  check-generated:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            make generate
            git diff --output /dev/null --exit-code helm/ || (echo 'Detected changes in generated files. Please run "make generate" and push again' && exit 1)
workflows:
  package-and-push-chart-on-tag:
    jobs:
      - check-generated:
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-sloth-rules-to-control-plane-catalog-master
          context: "architect"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "sloth-rules"
          requires:
            - check-generated
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
      
      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_catalog: control-plane-catalog
          app_name: "sloth-rules"
          app_namespace: monitoring
          app_collection_repo: "aws-app-collection"
          requires:
            - push-sloth-rules-to-control-plane-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: azure-app-collection
          context: "architect"
          app_catalog: control-plane-catalog
          app_name: "sloth-rules"
          app_namespace: monitoring
          app_collection_repo: "azure-app-collection"
          requires:
            - push-sloth-rules-to-control-plane-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: vsphere-app-collection
          context: "architect"
          app_catalog: control-plane-catalog
          app_name: "sloth-rules"
          app_namespace: monitoring
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-sloth-rules-to-control-plane-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:

          context: architect
          name: push-to-cloud-director-app-collection
          app_catalog: control-plane-catalog
          app_name: "sloth-rules"
          app_namespace: monitoring
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-sloth-rules-to-control-plane-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_catalog: control-plane-catalog
          app_name: "sloth-rules"
          app_namespace: monitoring
          app_collection_repo: "capa-app-collection"
          requires:
            - push-sloth-rules-to-control-plane-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-gcp-app-collection
          app_catalog: control-plane-catalog
          app_name: "sloth-rules"
          app_namespace: monitoring
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-sloth-rules-to-control-plane-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/()
