{{ $currentScope := . }}
{{ $providerFiles := .Files.Glob (printf "files/%s/**.yaml" .Values.provider) }}
{{ $commonFiles := .Files.Glob "files/all/**.yaml" }}
{{ range $path, $_ := $providerFiles  }}
---
  {{- with $currentScope}}
    {{ .Files.Get $path }}
  {{- end }}
{{ end }}
{{ range $path, $_ := $commonFiles  }}
---
  {{- with $currentScope}}
    {{ .Files.Get $path }}
  {{- end }}
{{ end }}
