apiVersion: v2
name: slos
description: SLO definition and implementation for Giant Swarm infrastructure
type: application
home: https://github.com/giantswarm/slo
kubeVersion: ">= 1.19.0-0"
version: 10.0.0
