apiVersion: v2
name: slos-poc
description: SLO definition and implementation for Giant Swarm infrastructure
type: application
home: https://github.com/giantswarm/slos-poc
kubeVersion: ">= 1.19.0-0"
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: phoenix
